# Generated by Django 4.2 on 2023-04-28 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_optedchoice_marks_optedchoice_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='attemptedtest',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
